- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_signup.scss
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
I've created the views for devise in so we have files for the signup page, new edit and all that good stuff that devise does automatically . 
I also aligned the form for sign up
it looked liked this ...
now it looks like this ....
> finished allinging sign up form and added views for devise

- app/controllers/superpowers_controller.rb
- app/views/superpowers/edit.html.erb
- config/routes.rb
I've added the edit and update functionality in the superpowers controller and also the view for the edit form.
> Superpower edit update methods and views

- app/controllers/superpowers_controller.rb
adding the destroy function in superpowers controller
> delete function in super power controller

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/superpowers_controller.rb
- app/models/superpower.rb
- app/views/layouts/application.html.erb
- app/views/superpowers/index.html.erb
- app/views/superpowers/show.html.erb
Start the styling of index and show. Is going this way
> working on style in index and show

- app/views/bookings/new.html.erb
- app/views/superpowers/show.html.erb
Have added a booking button on the super power show page and also a back button the booking form that takes you back to the show page.
> adding booking button on superpower and add back button on booking

- app/controllers/reviews_controller.rb
- app/models/booking.rb
- app/models/review.rb
- app/models/user.rb
- app/views/reviews/create.html.erb
- app/views/reviews/new.html.erb
- db/migrate/20190821101927_add_bookings_id_to_bookings.rb
- db/migrate/20190821103234_add_user_to_review.rb
- db/schema.rb
Hi guys!
Implemented create new review.
This meant I had to change the DB schema as we spoke about with Andrey (added bookings_id and user_id column to review table and also removed review_id column from bookings table). Bookings has_one review + review belongs to booking
All works! 🙌🏼
> Create new review

- app/controllers/superpowers_controller.rb
- app/models/superpower.rb
- app/views/superpowers/show.html.erb
- db/schema.rb
- db/seeds.rb
have added reviews to the show for each super power
> Adding reviews to show for superheros

- app/views/pages/home.html.erb
> fixed grammar

- app/models/superpower.rb
- app/views/layouts/application.html.erb
Ive added availability to the data base in the superpower model, i updated the create method so that this is availbility is set to true when a new super power is created.
> Make photo validation necessary for superpower

- app/views/superpowers/new.html.erb
> gave a little style to /superpower/new

- app/views/superpowers/show.html.erb
> removed edit and destroy buttons from show page

- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/pages/dashboard.html.erb
- app/views/superpowers/index.html.erb
- app/views/superpowers/new.html.erb
- app/views/superpowers/show.html.erb
- app/views/users/edit.html.erb
> all the buttons with the new color except the 'select file' ones

- app/views/bookings/new.html.erb
> gived some style to booking/new

- Gemfile
- Gemfile.lock
- app/controllers/bookings_controller.rb
- app/models/booking.rb
- app/views/pages/dashboard.html.erb
- app/views/pages/home.html.erb
Log in Logout Avatar dashboard is back on landing page
and booking validation is installed in BOoking model
> Bookingdatechange

- Gemfile
- app/assets/stylesheets/components/_forms.scss
- app/views/pages/dashboard.html.erb
- app/views/reviews/new.html.erb
> create review is now styled

- Gemfile
- Gemfile.lock
- app/controllers/superpowers_controller.rb
- app/models/superpower.rb
- config/initializers/elasticsearch.rb
- db/migrate/20190823094627_create_pg_search_documents.rb
- db/schema.rb
changed to pg search for ease of use.
> Change search to pgsearch

- app/views/superpowers/edit.html.erb
fixed edit superpower form so it isnt wonky!
> fixed form for edit superpower

- app/controllers/superpowers_controller.rb
- app/views/superpowers/show.html.erb
> Showpage w booking form

- app/views/users/edit.html.erb
changed saved on edit user form
> done with save change

- app/assets/stylesheets/components/_dashboard.scss
- app/controllers/superpowers_controller.rb
- app/models/superpower.rb
- app/views/pages/dashboard.html.erb
- db/seeds.rb
Guys. changed the dashboard. 
All functioning buttons. will make styling little nicer. 
TRY TO DESTROY THE superpower that already has bookings. It will say something different!
> Dashboardstyle

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_footer.scss
- app/views/pages/home.html.erb
> added cards with customers reviews and footer to landing page

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_show.scss
- app/controllers/superpowers_controller.rb
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/superpower.rb
- app/views/layouts/application.html.erb
- app/views/superpowers/show.html.erb
- config/initializers/geocoder.rb
- db/migrate/20190823103643_add_address_to_superpowers.rb
- db/migrate/20190823103953_add_latitude_to_superpowers.rb
- db/migrate/20190823104011_add_longitude_to_superpowers.rb
- db/schema.rb
- db/seeds.rb
- package.json
- yarn.lock
couldnt get map working going to come back to it
> Add map functionality to show
